main:
  allow-bean-definition-overriding: true

spring:
  data:
    mongodb:
      uri: mongodb+srv://tlcn_user:bookwebsite@cluster0.jmrvw.mongodb.net/BookStore

server:
  port: 8082

book-service:
  base-url: http://localhost:8081