server:
  port: 8083

spring:
  data:
    mongodb:
      uri: mongodb+srv://tlcn_user:tlcn_bookstore@cluster0.jmrvw.mongodb.net/BookStore
  main:
    allow-bean-definition-overriding: true

app:
  api:
    openrouter-key: "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"