server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:file:C:/Users/Thanh Hung/test;AUTO_SERVER=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true